---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cve-vs
  namespace: istio-system
spec:
  hosts:
  - "cve.dev.anuragnandre.online"
  gateways:
  - istio-system/observability-gateway
  http:
  - name: "cve-gpt-vs"
    match:
    - uri:
        exact: "/"
    route:
    - destination:
        host: rag-service.webapp-consumer.svc.cluster.local
        port:
          number: 8501