---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    meta.helm.sh/release-namespace: istio-system
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email:  nandre.a@northeastern.edu
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        route53:
          region: us-east-1
          hostedZoneID: "Z03371893NFK1E5ROZ2OY"
      selector:
        dnsZones:
          - "dev.anuragnandre.online"
          
