---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cve-destination-rule
  namespace: istio-system
spec:
  host: cve-rag-cve-intelligence.cve-rag.svc.cluster.local
  subsets:
  - name: regular
    labels:
      app: cve-rag-cve-intelligence
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cve-destination-rule-light
  namespace: istio-system
spec:
  host: cve-rag--light-cve-intelligence.cve-rag.svc.cluster.local
  subsets:
  - name: light
    labels:
      app: cve-rag--light-cve-intelligence
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cve-vs
  namespace: istio-system
spec:
  hosts:
  - "cve.dev.anuragnandre.online"
  gateways:
  - istio-system/observability-gateway
  http:
  - name: "cve-gpt-vs"
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: cve-rag-cve-intelligence.cve-rag.svc.cluster.local
        port:
          number: 8501
      weight: 50
    - destination:
        host: cve-rag-light-cve-intelligence.cve-rag.svc.cluster.local
        port:
          number: 8501
      weight: 50