---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email:  nandre.a@northeastern.edu
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        route53:
          region: us-east-1
          hostedZoneID: "Z03371893NFK1E5ROZ2OY"
          role: arn:aws:iam::533267416279:role/cert_manager_role
      selector:
        dnsZones:
          - "dev.anuragnandre.online"
          
